export const categories = [
  { id: "1", name: "Business", icon: "business" },
  { id: "2", name: "Entertainment", icon: "movie" },
  { id: "3", name: "Health", icon: "health-and-safety" },
  { id: "4", name: "Science", icon: "science" },
  { id: "5", name: "Sports", icon: "sports" },
  { id: "6", name: "Technology", icon: "computer" },
  { id: "7", name: "Headlines", icon: "newspaper" },
  { id: "8", name: "Everything", icon: "newspaper" },
  { id: "9", name: "Covid-19", icon: "medical-services" },
  { id: "10", name: "Coronavirus", icon: "medical-services" },
  { id: "11", name: "Finance", icon: "monetization-on" },
  { id: "12", name: "Food", icon: "restaurant" },
  { id: "13", name: "Travel", icon: "flight" },
  { id: "14", name: "Music", icon: "music-note" },
  { id: "15", name: "TV", icon: "tv" },
  { id: "16", name: "Books", icon: "book" },
  { id: "17", name: "Gaming", icon: "videogame-asset" },
  { id: "18", name: "Movies", icon: "movie" },
  { id: "19", name: "News", icon: "newspaper" },
  { id: "20", name: "Pets", icon: "pets" },
  { id: "21", name: "Sports", icon: "sports" },
  { id: "22", name: "Vehicles", icon: "directions-car" },
];
