export const countries = [
  { id: "1", name: "United Arab Emirates", code: "ae", icon: "flag" },
  { id: "2", name: "Argentina", code: "ar", icon: "flag" },
  { id: "3", name: "Australia", code: "au", icon: "flag" },
  { id: "4", name: "Belgium", code: "be", icon: "flag" },
  { id: "5", name: "Bulgaria", code: "bg", icon: "flag" },
  { id: "6", name: "Brazil", code: "br", icon: "flag" },
  { id: "7", name: "Canada", code: "ca", icon: "flag" },
  { id: "8", name: "Switzerland", code: "ch", icon: "flag" },
  { id: "9", name: "China", code: "cn", icon: "flag" },
  { id: "10", name: "Colombia", code: "co", icon: "flag" },
  { id: "11", name: "Cuba", code: "cu", icon: "flag" },
  { id: "12", name: "Czech Republic", code: "cz", icon: "flag" },
  { id: "13", name: "Germany", code: "de", icon: "flag" },
  { id: "14", name: "Egypt", code: "eg", icon: "flag" },
  { id: "15", name: "France", code: "fr", icon: "flag" },
  { id: "16", name: "United Kingdom", code: "gb", icon: "flag" },
  { id: "17", name: "Greece", code: "gr", icon: "flag" },
  { id: "18", name: "Hong Kong", code: "hk", icon: "flag" },
  { id: "19", name: "Hungary", code: "hu", icon: "flag" },
  { id: "20", name: "India", code: "in", icon: "flag" },
  { id: "21", name: "Indonesia", code: "id", icon: "flag" },
  { id: "22", name: "Ireland", code: "ie", icon: "flag" },
  { id: "23", name: "Israel", code: "il", icon: "flag" },
  { id: "24", name: "Italy", code: "it", icon: "flag" },
  { id: "25", name: "Japan", code: "jp", icon: "flag" },
  { id: "26", name: "Latvia", code: "lv", icon: "flag" },
  { id: "27", name: "Nigeria", code: "ng", icon: "flag" },
  { id: "28", name: "USA", code: "us", icon: "flag" },
];
